-- =============================================
-- RECRIAR PARQUET COM NOMES DE COLUNAS ASCII
-- =============================================

SET memory_limit = '32GB';
SET threads = 8;

-- Cria um novo Parquet com nomes de colunas limpos
COPY (
    SELECT 
        municipio AS municipio,
        cnae_95_classe AS cnae_95_classe,
        vinculo_ativo AS vinculo_ativo,
        tp_vinculo AS tp_vinculo,
        motivo_desligamento AS motivo_desligamento,
        mes_desligamento AS mes_desligamento,
        ind_vinculo_alvara AS ind_vinculo_alvara,
        tipo_admissao AS tipo_admissao,
        tipo_salario AS tipo_salario,
        escolaridade AS escolaridade,
        sexo_trabalhador AS sexo_trabalhador,
        nacionalidade AS nacionalidade,
        raca_cor AS raca_cor,
        portador_deficiencia AS portador_deficiencia,
        porte_estabelecimento AS porte_estabelecimento,
        natureza_juridica AS natureza_juridica,
        ind_cei_vinculado AS ind_cei_vinculado,
        tp_estabelecimento AS tp_estabelecimento,
        ind_estabelecimento_pat AS ind_estabelecimento_pat,
        ind_part_simples AS ind_part_simples,
        dt_admissao AS dt_admissao,
        vl_remuneracao_media_declarada AS vl_remuneracao_media_declarada,
        valor_salario_medio AS valor_salario_medio,
        vl_remun_dezembro_nom AS vl_remun_dezembro_nom,
        vl_remun_rezembro_sm AS vl_remun_rezembro_sm,
        tempo_emprego AS tempo_emprego,
        qtd_horas_contratadas AS qtd_horas_contratadas,
        vl_ult_salario AS vl_ult_salario,
        vl_sal_contratado AS vl_sal_contratado,
        nm_pis AS nm_pis,
        dt_nasc AS dt_nasc,
        numero_ctps AS numero_ctps,
        cpf AS cpf,
        cei_vinculado AS cei_vinculado,
        cnpj_cei AS cnpj_cei,
        cnpj_raiz AS cnpj_raiz,
        nm_trabalhador AS nm_trabalhador,
        cbo AS cbo,
        cnae_classe AS cnae_classe,
        cnae_subclasse AS cnae_subclasse,
        tipo_defic AS tipo_defic,
        causa_afastamento_01 AS causa_afastamento_01,
        dia_ini_af1 AS dia_ini_af1,
        mes_ini_af1 AS mes_ini_af1,
        dia_fim_af1 AS dia_fim_af1,
        mes_fim_af1 AS mes_fim_af1,
        causa_afastamento_02 AS causa_afastamento_02,
        dia_ini_af2 AS dia_ini_af2,
        mes_ini_af2 AS mes_ini_af2,
        dia_fim_af2 AS dia_fim_af2,
        mes_fim_af2 AS mes_fim_af2,
        causa_afastamento_03 AS causa_afastamento_03,
        dia_ini_af3 AS dia_ini_af3,
        mes_ini_af3 AS mes_ini_af3,
        dia_fim_af3 AS dia_fim_af3,
        mes_fim_af3 AS mes_fim_af3,
        qtd_dias_afastamento AS qtd_dias_afastamento,
        idade AS idade,
        dia_desligamento AS dia_desligamento,
        ibge_subsetor AS ibge_subsetor,
        ano_chegada_brasil AS ano_chegada_brasil,
        cep_estabelecimento AS cep_estabelecimento,
        municipio_trabalhado AS municipio_trabalhado,
        razao_social AS razao_social,
        vl_rem_janeiro_sc AS vl_rem_janeiro_sc,
        vl_rem_fevereiro_sc AS vl_rem_fevereiro_sc,
        vl_rem_marco_sc AS vl_rem_marco_sc,
        vl_rem_abril_sc AS vl_rem_abril_sc,
        vl_rem_maio_sc AS vl_rem_maio_sc,
        vl_rem_junho_sc AS vl_rem_junho_sc,
        vl_rem_julho_sc AS vl_rem_julho_sc,
        vl_rem_agosto_sc AS vl_rem_agosto_sc,
        vl_rem_setembro_sc AS vl_rem_setembro_sc,
        vl_rem_outubro_sc AS vl_rem_outubro_sc,
        vl_rem_novembro_sc AS vl_rem_novembro_sc,
        ind_trab_intermitente AS ind_trab_intermitente,
        ind_trab_parcial AS ind_trab_parcial
    FROM 'dados_completo.parquet'
) TO 'dados_ascii.parquet' (FORMAT PARQUET, COMPRESSION ZSTD);