USE [master]
GO
CREATE LOGIN [SafeBaseAPI_app] WITH PASSWORD=N'sfew1@33www', DEFAULT_DATABASE=[SafeBaseAPI], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [SafeBaseAPI]
GO
CREATE USER [SafeBaseAPI_app] FOR LOGIN [SafeBaseAPI_app]
GO
USE [SafeBaseAPI]
GO
ALTER USER [SafeBaseAPI_app] WITH DEFAULT_SCHEMA=[dbo], LOGIN=[SafeBaseAPI_app]
GO
USE [SafeBaseAPI]
GO
ALTER ROLE [db_owner] ADD MEMBER [SafeBaseAPI_app]
GO
